### ISSUE TITLE
Command Line_

### ISSUE THREAD

**Issue by alsab200** [0xC0000054/pdn-riot#1]
Hi. Thank you for this great plugin.. Is there a way to run this from command line? (thru command line pdn for instance)
Riot, I love it, I wish there was a command line option for it..
Thats why I came here.. Just hoping..
Thank you.

**Comment by 0xC0000054** [comment]
Paint.NET does not support command line automation or batch processing,

The main download on the [RIOT website](https://riot-optimizer.com/) does have a batch processing option in the UI, but I do not know if it can be fully automated from the command line.

**Comment by alsab200** [comment]
prompt reply; prompt(er) "closing" to allow a "thank you" though..
regardless.. thanks.
